from exceptions_project.simple_calculator.input_handler import get_number
from exceptions_project.simple_calculator.input_handler import get_operation
from exceptions_project.simple_calculator.validator import validate_division
from exceptions_project.simple_calculator.validator import validate_operation
from exceptions_project.simple_calculator.operations import calculate
