# Generated by Django 6.1.1 on 2026-09-18 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_event_capacity_gte_0'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='event_capacity_gte_0',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='event_capacity_gt_0'),
        ),
    ]
