"""align schema with ORM models

Revision ID: 9ef4cbc8882b
Revises: ed0fbc1ca00f
Create Date: 2026-07-11 20:00:26.627605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef4cbc8882b'
down_revision: Union[str, Sequence[str], None] = 'ed0fbc1ca00f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=False)

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
